
`timescale 1ns / 1ps
`default_nettype none
// Auto-generated by test_axis_rgb_dog.py. Instantiates the three DoG DUTs exactly as
// verification/tb/tb_axis_rgb_dog.sv does (conv LINE_PIXELS=8 ENABLE=1; combine ENABLE=1
// DEPTH=64) and exposes the driving ports so cocotb can drive the chain top.
module dog_chain_top #(
    parameter int W = 8
)(
    input  wire         clk,
    input  wire         rst_n,
    input  wire [23:0]  in_pixel,
    input  wire         in_valid,
    input  wire         in_sof,
    input  wire         in_eol,
    input  wire         in_eof,
    input  wire         in_err,
    input  wire [71:0]  a_coeffs,
    input  wire [3:0]   a_shift,
    input  wire         a_en,
    input  wire [199:0] b_coeffs,
    input  wire [3:0]   b_shift,
    input  wire         b_en,
    input  wire [1:0]   cfg_mode,
    input  wire [7:0]   cfg_alpha,
    input  wire [7:0]   cfg_beta,
    input  wire [3:0]   cfg_shift,
    input  wire signed [8:0] cfg_offset,
    output wire [23:0]  out_pixel,
    output wire         out_valid,
    output wire         out_sof,
    output wire         out_eol,
    output wire         out_eof,
    output wire         out_err
);
    wire [23:0] a_pixel; wire a_valid, a_sof, a_eol, a_eof, a_err;
    wire [23:0] b_pixel; wire b_valid, b_sof, b_eol, b_eof, b_err;

    axis_rgb_conv3x3 #(.LINE_PIXELS(W), .ENABLE(1'b1)) uA (
        .clk(clk), .rst_n(rst_n), .cfg_en(a_en), .cfg_coeffs(a_coeffs),
        .cfg_shift(a_shift), .cfg_abs(1'b0),
        .in_pixel(in_pixel), .in_valid(in_valid), .in_sof(in_sof),
        .in_eol(in_eol), .in_eof(in_eof), .in_err(in_err),
        .out_pixel(a_pixel), .out_valid(a_valid), .out_sof(a_sof),
        .out_eol(a_eol), .out_eof(a_eof), .out_err(a_err)
    );
    axis_rgb_conv5x5 #(.LINE_PIXELS(W), .ENABLE(1'b1)) uB (
        .clk(clk), .rst_n(rst_n), .cfg_en(b_en), .cfg_coeffs(b_coeffs),
        .cfg_shift(b_shift), .cfg_abs(1'b0),
        .in_pixel(in_pixel), .in_valid(in_valid), .in_sof(in_sof),
        .in_eol(in_eol), .in_eof(in_eof), .in_err(in_err),
        .out_pixel(b_pixel), .out_valid(b_valid), .out_sof(b_sof),
        .out_eol(b_eol), .out_eof(b_eof), .out_err(b_err)
    );
    axis_rgb_dog_combine #(.ENABLE(1'b1), .DEPTH(64)) uC (
        .clk(clk), .rst_n(rst_n),
        .cfg_mode(cfg_mode), .cfg_alpha(cfg_alpha), .cfg_beta(cfg_beta),
        .cfg_shift(cfg_shift), .cfg_offset(cfg_offset),
        .a_pixel(a_pixel), .a_valid(a_valid),
        .b_pixel(b_pixel), .b_valid(b_valid),
        .b_sof(b_sof), .b_eol(b_eol), .b_eof(b_eof), .b_err(b_err),
        .out_pixel(out_pixel), .out_valid(out_valid), .out_sof(out_sof),
        .out_eol(out_eol), .out_eof(out_eof), .out_err(out_err)
    );
endmodule
`default_nettype wire
