#*****************************************************************************************
# Vivado (TM) v2024.2 (64-bit)
#
# vloop_probes2_recreate.tcl: Tcl script for re-creating project 'vloop'
#
# Generated by Vivado on Sat Jun 20 05:14:22 +0900 2026
# IP Build 5239520 on Sun Nov 10 16:12:51 MST 2024
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (vloop_probes2_recreate.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    <none>
#
# 3. The following remote source files that were added to the original project:-
#
#    "$origin_dir/../rtl/img_proc/axis_y8_to_vdma32.sv"
#    "$origin_dir/../rtl/img_proc/axis_y8_to_vdma32_ref.v"
#    "$origin_dir/../rtl/img_proc/axis_vdma32_to_y8.sv"
#    "$origin_dir/../rtl/img_proc/axis_vdma32_to_y8_ref.v"
#    "$origin_dir/../rtl/mipi_rx/axis_video_bridge.sv"
#    "$origin_dir/../rtl/mipi_rx/byte_to_core_cdc.sv"
#    "$origin_dir/../rtl/mipi_rx/csi2_frame_state.sv"
#    "$origin_dir/../rtl/mipi_rx/csi2_header_ecc.sv"
#    "$origin_dir/../rtl/mipi_rx/csi2_packet_parser.sv"
#    "$origin_dir/../rtl/mipi_rx/csi2_payload_crc.sv"
#    "$origin_dir/../rtl/prototype/csi2_tpg.sv"
#    "$origin_dir/../rtl/mipi_rx/csi2_vcdt_filter.sv"
#    "$origin_dir/../rtl/mipi_rx/dphy_cdc_prims.sv"
#    "$origin_dir/../rtl/prototype/dphy_hs_byte_probe.sv"
#    "$origin_dir/../rtl/mipi_rx/dphy_hwlock_fsm.sv"
#    "$origin_dir/../rtl/mipi_rx/dphy_lane_supervisor.sv"
#    "$origin_dir/../rtl/prototype/dphy_raw_byte_ringbuf.sv"
#    "$origin_dir/../rtl/hdmi/hdmi_output.sv"
#    "$origin_dir/../rtl/hdmi/hdmi_tpg_top.sv"
#    "$origin_dir/../rtl/prototype/mipi_to_hdmi_probe_top.sv"
#    "$origin_dir/../rtl/img_proc/ob_row_masker.sv"
#    "$origin_dir/../rtl/prototype/ov5640_sccb_init_probe.sv"
#    "$origin_dir/../rtl/img_proc/raw10_unpack.sv"
#    "$origin_dir/../rtl/img_proc/raw8_passthrough.sv"
#    "$origin_dir/../rtl/img_proc/rgb565_gray_unpack.sv"
#    "$origin_dir/../rtl/img_proc/video_frame_normalizer.sv"
#    "$origin_dir/../rtl/img_proc/yuv422_crc_framebuffer_axis.sv"
#    "$origin_dir/../rtl/img_proc/yuv422_gray_unpack.sv"
#    "$origin_dir/../rtl/prototype/mipi_to_hdmi_vdma_loop_ref.v"
#    "$origin_dir/../vivado/constraints/mipi_to_hdmi_probe.xdc"
#    "$origin_dir/../vivado/constraints/vdma_loop_clock_groups.xdc"
#
#*****************************************************************************************

# Check file required for this script exists
proc checkRequiredFiles { origin_dir} {
  set status true
  set files [list \
 "[file normalize "$origin_dir/../rtl/img_proc/axis_y8_to_vdma32.sv"]"\
 "[file normalize "$origin_dir/../rtl/img_proc/axis_y8_to_vdma32_ref.v"]"\
 "[file normalize "$origin_dir/../rtl/img_proc/axis_vdma32_to_y8.sv"]"\
 "[file normalize "$origin_dir/../rtl/img_proc/axis_vdma32_to_y8_ref.v"]"\
 "[file normalize "$origin_dir/../rtl/mipi_rx/axis_video_bridge.sv"]"\
 "[file normalize "$origin_dir/../rtl/mipi_rx/byte_to_core_cdc.sv"]"\
 "[file normalize "$origin_dir/../rtl/mipi_rx/csi2_frame_state.sv"]"\
 "[file normalize "$origin_dir/../rtl/mipi_rx/csi2_header_ecc.sv"]"\
 "[file normalize "$origin_dir/../rtl/mipi_rx/csi2_packet_parser.sv"]"\
 "[file normalize "$origin_dir/../rtl/mipi_rx/csi2_payload_crc.sv"]"\
 "[file normalize "$origin_dir/../rtl/prototype/csi2_tpg.sv"]"\
 "[file normalize "$origin_dir/../rtl/mipi_rx/csi2_vcdt_filter.sv"]"\
 "[file normalize "$origin_dir/../rtl/mipi_rx/dphy_cdc_prims.sv"]"\
 "[file normalize "$origin_dir/../rtl/prototype/dphy_hs_byte_probe.sv"]"\
 "[file normalize "$origin_dir/../rtl/mipi_rx/dphy_hwlock_fsm.sv"]"\
 "[file normalize "$origin_dir/../rtl/mipi_rx/dphy_lane_supervisor.sv"]"\
 "[file normalize "$origin_dir/../rtl/prototype/dphy_raw_byte_ringbuf.sv"]"\
 "[file normalize "$origin_dir/../rtl/hdmi/hdmi_output.sv"]"\
 "[file normalize "$origin_dir/../rtl/hdmi/hdmi_tpg_top.sv"]"\
 "[file normalize "$origin_dir/../rtl/prototype/mipi_to_hdmi_probe_top.sv"]"\
 "[file normalize "$origin_dir/../rtl/img_proc/ob_row_masker.sv"]"\
 "[file normalize "$origin_dir/../rtl/prototype/ov5640_sccb_init_probe.sv"]"\
 "[file normalize "$origin_dir/../rtl/img_proc/raw10_unpack.sv"]"\
 "[file normalize "$origin_dir/../rtl/img_proc/raw8_passthrough.sv"]"\
 "[file normalize "$origin_dir/../rtl/img_proc/rgb565_gray_unpack.sv"]"\
 "[file normalize "$origin_dir/../rtl/img_proc/video_frame_normalizer.sv"]"\
 "[file normalize "$origin_dir/../rtl/img_proc/yuv422_crc_framebuffer_axis.sv"]"\
 "[file normalize "$origin_dir/../rtl/img_proc/yuv422_gray_unpack.sv"]"\
 "[file normalize "$origin_dir/../rtl/prototype/mipi_to_hdmi_vdma_loop_ref.v"]"\
 "[file normalize "$origin_dir/constraints/mipi_to_hdmi_probe.xdc"]"\
 "[file normalize "$origin_dir/constraints/vdma_loop_clock_groups.xdc"]"\
  ]
  foreach ifile $files {
    if { ![file isfile $ifile] } {
      puts " Could not find remote file $ifile "
      set status false
    }
  }

  return $status
}
# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir [file dirname [file normalize [info script]]]

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

# Set the project name
set _xil_proj_name_ "vloop"

# Use project name variable, if specified in the tcl shell
if { [info exists ::user_project_name] } {
  set _xil_proj_name_ $::user_project_name
}

variable script_file
set script_file "vloop_probes2_recreate.tcl"

# Help information for this script
proc print_help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--project_name <name>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--project_name <name>\] Create project with the specified name. Default"
  puts "                       name is the name of the project from where this"
  puts "                       script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < $::argc} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir"   { incr i; set origin_dir [lindex $::argv $i] }
      "--project_name" { incr i; set _xil_proj_name_ [lindex $::argv $i] }
      "--help"         { print_help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/../vloop_probes2"]"

# Check for paths and files needed for project creation
set validate_required 0
if { $validate_required } {
  if { [checkRequiredFiles $origin_dir] } {
    puts "Tcl file $script_file is valid. All files required for project creation is accesable. "
  } else {
    puts "Tcl file $script_file is not valid. Not all files required for project creation is accesable. "
    return
  }
}

# Create project
create_project ${_xil_proj_name_} ./${_xil_proj_name_} -part xc7z020clg400-1

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Reconstruct message rules
set_msg_config  -id {Ip 78-90}  -new_severity {WARNING}  -ruleid {1}  -source 2
set_msg_config  -id {BD 41-69}  -new_severity {WARNING}  -ruleid {2}  -source 2
set_msg_config  -id {Common 17-232}  -new_severity {WARNING}  -ruleid {3}  -source 2
set_msg_config  -id {IP_Flow 19-883}  -new_severity {WARNING}  -ruleid {4}  -source 2
set_msg_config  -id {IP_Flow 19-3428}  -new_severity {WARNING}  -ruleid {5}  -source 2


# Set project properties
set obj [current_project]
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "enable_resource_estimation" -value "0" -objects $obj
set_property -name "enable_vhdl_2008" -value "1" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/${_xil_proj_name_}.cache/ip" -objects $obj
set_property -name "mem.enable_memory_map_generation" -value "1" -objects $obj
set_property -name "part" -value "xc7z020clg400-1" -objects $obj
set_property -name "revised_directory_structure" -value "1" -objects $obj
set_property -name "sim.central_dir" -value "$proj_dir/${_xil_proj_name_}.ip_user_files" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "sim_compile_state" -value "1" -objects $obj
set_property -name "use_inline_hdl_ip" -value "1" -objects $obj
set_property -name "xpm_libraries" -value "XPM_CDC XPM_FIFO XPM_MEMORY" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/../rtl/img_proc/axis_y8_to_vdma32.sv"] \
 [file normalize "${origin_dir}/../rtl/img_proc/axis_y8_to_vdma32_ref.v"] \
 [file normalize "${origin_dir}/../rtl/img_proc/axis_vdma32_to_y8.sv"] \
 [file normalize "${origin_dir}/../rtl/img_proc/axis_vdma32_to_y8_ref.v"] \
 [file normalize "${origin_dir}/../rtl/mipi_rx/axis_video_bridge.sv"] \
 [file normalize "${origin_dir}/../rtl/mipi_rx/byte_to_core_cdc.sv"] \
 [file normalize "${origin_dir}/../rtl/mipi_rx/csi2_frame_state.sv"] \
 [file normalize "${origin_dir}/../rtl/mipi_rx/csi2_header_ecc.sv"] \
 [file normalize "${origin_dir}/../rtl/mipi_rx/csi2_packet_parser.sv"] \
 [file normalize "${origin_dir}/../rtl/mipi_rx/csi2_payload_crc.sv"] \
 [file normalize "${origin_dir}/../rtl/prototype/csi2_tpg.sv"] \
 [file normalize "${origin_dir}/../rtl/mipi_rx/csi2_vcdt_filter.sv"] \
 [file normalize "${origin_dir}/../rtl/mipi_rx/dphy_cdc_prims.sv"] \
 [file normalize "${origin_dir}/../rtl/prototype/dphy_hs_byte_probe.sv"] \
 [file normalize "${origin_dir}/../rtl/mipi_rx/dphy_hwlock_fsm.sv"] \
 [file normalize "${origin_dir}/../rtl/mipi_rx/dphy_lane_supervisor.sv"] \
 [file normalize "${origin_dir}/../rtl/prototype/dphy_raw_byte_ringbuf.sv"] \
 [file normalize "${origin_dir}/../rtl/hdmi/hdmi_output.sv"] \
 [file normalize "${origin_dir}/../rtl/hdmi/hdmi_tpg_top.sv"] \
 [file normalize "${origin_dir}/../rtl/prototype/mipi_to_hdmi_probe_top.sv"] \
 [file normalize "${origin_dir}/../rtl/img_proc/ob_row_masker.sv"] \
 [file normalize "${origin_dir}/../rtl/prototype/ov5640_sccb_init_probe.sv"] \
 [file normalize "${origin_dir}/../rtl/img_proc/raw10_unpack.sv"] \
 [file normalize "${origin_dir}/../rtl/img_proc/raw8_passthrough.sv"] \
 [file normalize "${origin_dir}/../rtl/img_proc/rgb565_gray_unpack.sv"] \
 [file normalize "${origin_dir}/../rtl/img_proc/video_frame_normalizer.sv"] \
 [file normalize "${origin_dir}/../rtl/img_proc/yuv422_crc_framebuffer_axis.sv"] \
 [file normalize "${origin_dir}/../rtl/img_proc/yuv422_gray_unpack.sv"] \
 [file normalize "${origin_dir}/../rtl/prototype/mipi_to_hdmi_vdma_loop_ref.v"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/../rtl/img_proc/axis_y8_to_vdma32.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../rtl/img_proc/axis_vdma32_to_y8.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../rtl/mipi_rx/axis_video_bridge.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../rtl/mipi_rx/byte_to_core_cdc.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../rtl/mipi_rx/csi2_frame_state.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../rtl/mipi_rx/csi2_header_ecc.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../rtl/mipi_rx/csi2_packet_parser.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../rtl/mipi_rx/csi2_payload_crc.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../rtl/prototype/csi2_tpg.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../rtl/mipi_rx/csi2_vcdt_filter.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../rtl/mipi_rx/dphy_cdc_prims.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../rtl/prototype/dphy_hs_byte_probe.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../rtl/mipi_rx/dphy_hwlock_fsm.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../rtl/mipi_rx/dphy_lane_supervisor.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../rtl/prototype/dphy_raw_byte_ringbuf.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../rtl/hdmi/hdmi_output.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../rtl/hdmi/hdmi_tpg_top.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../rtl/prototype/mipi_to_hdmi_probe_top.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../rtl/img_proc/ob_row_masker.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../rtl/prototype/ov5640_sccb_init_probe.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../rtl/img_proc/raw10_unpack.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../rtl/img_proc/raw8_passthrough.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../rtl/img_proc/rgb565_gray_unpack.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../rtl/img_proc/video_frame_normalizer.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../rtl/img_proc/yuv422_crc_framebuffer_axis.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../rtl/img_proc/yuv422_gray_unpack.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property -name "dataflow_viewer_settings" -value "min_width=16" -objects $obj
set_property -name "generic" -value "PROBE_IDELAY_TAP=8 PROBE_LANE1_BITSLIP_SWEEP=0 STREAM_PAIRING=0 OV5640_MIPI_CTRL_4800=36 OV5640_FORMAT_CTRL_4300=48 OV5640_ISP_CTRL_5000=167 OV5640_ISP_CTRL_5001=131 OV5640_TEST_PATTERN_ENABLE=0 CAPTURE_RAW_PAYLOAD=0 USE_RGB565_GRAY=0 IMAGE_FORMAT=0" -objects $obj
set_property -name "top" -value "bd_wrapper" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj
set_property -name "verilog_define" -value "MIPI_CAPTURE_PORTS MIPI_VDMA_LOOP_PORTS" -objects $obj
set_property -name "vhdl_generic" -value "PROBE_IDELAY_TAP=8 PROBE_LANE1_BITSLIP_SWEEP=0 STREAM_PAIRING=0 OV5640_MIPI_CTRL_4800=36 OV5640_FORMAT_CTRL_4300=48 OV5640_ISP_CTRL_5000=167 OV5640_ISP_CTRL_5001=131 OV5640_TEST_PATTERN_ENABLE=0 CAPTURE_RAW_PAYLOAD=0 USE_RGB565_GRAY=0 IMAGE_FORMAT=0" -objects $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/constraints/mipi_to_hdmi_probe.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/constraints/mipi_to_hdmi_probe.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/constraints/vdma_loop_clock_groups.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/constraints/vdma_loop_clock_groups.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj
set_property -name "used_in" -value "implementation" -objects $file_obj
set_property -name "used_in_synthesis" -value "0" -objects $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]
set_property -name "target_part" -value "xc7z020clg400-1" -objects $obj

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
# Empty (no sources present)

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property -name "sim_wrapper_top" -value "1" -objects $obj
set_property -name "top" -value "hdmi_tpg_top" -objects $obj
set_property -name "top_file" -value "../rtl/hdmi/hdmi_tpg_top.sv" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj

# Set 'utils_1' fileset object
set obj [get_filesets utils_1]
# Empty (no sources present)

# Set 'utils_1' fileset properties
set obj [get_filesets utils_1]


# Adding sources referenced in BDs, if not already added
if { [get_files [list axis_y8_to_vdma32.sv]] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../rtl/img_proc/axis_y8_to_vdma32.sv
}
if { [get_files [list axis_y8_to_vdma32_ref.v]] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../rtl/img_proc/axis_y8_to_vdma32_ref.v
}
if { [get_files [list axis_vdma32_to_y8.sv]] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../rtl/img_proc/axis_vdma32_to_y8.sv
}
if { [get_files [list axis_vdma32_to_y8_ref.v]] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../rtl/img_proc/axis_vdma32_to_y8_ref.v
}
if { [get_files [list axis_video_bridge.sv]] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../rtl/mipi_rx/axis_video_bridge.sv
}
if { [get_files [list byte_to_core_cdc.sv]] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../rtl/mipi_rx/byte_to_core_cdc.sv
}
if { [get_files [list csi2_frame_state.sv]] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../rtl/mipi_rx/csi2_frame_state.sv
}
if { [get_files [list csi2_header_ecc.sv]] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../rtl/mipi_rx/csi2_header_ecc.sv
}
if { [get_files [list csi2_packet_parser.sv]] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../rtl/mipi_rx/csi2_packet_parser.sv
}
if { [get_files [list csi2_payload_crc.sv]] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../rtl/mipi_rx/csi2_payload_crc.sv
}
if { [get_files [list csi2_tpg.sv]] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../rtl/prototype/csi2_tpg.sv
}
if { [get_files [list csi2_vcdt_filter.sv]] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../rtl/mipi_rx/csi2_vcdt_filter.sv
}
if { [get_files [list dphy_cdc_prims.sv]] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../rtl/mipi_rx/dphy_cdc_prims.sv
}
if { [get_files [list dphy_hs_byte_probe.sv]] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../rtl/prototype/dphy_hs_byte_probe.sv
}
if { [get_files [list dphy_hwlock_fsm.sv]] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../rtl/mipi_rx/dphy_hwlock_fsm.sv
}
if { [get_files [list dphy_lane_supervisor.sv]] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../rtl/mipi_rx/dphy_lane_supervisor.sv
}
if { [get_files [list dphy_raw_byte_ringbuf.sv]] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../rtl/prototype/dphy_raw_byte_ringbuf.sv
}
if { [get_files [list hdmi_output.sv]] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../rtl/hdmi/hdmi_output.sv
}
if { [get_files [list hdmi_tpg_top.sv]] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../rtl/hdmi/hdmi_tpg_top.sv
}
if { [get_files [list mipi_to_hdmi_probe_top.sv]] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../rtl/prototype/mipi_to_hdmi_probe_top.sv
}
if { [get_files [list ob_row_masker.sv]] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../rtl/img_proc/ob_row_masker.sv
}
if { [get_files [list ov5640_sccb_init_probe.sv]] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../rtl/prototype/ov5640_sccb_init_probe.sv
}
if { [get_files [list raw10_unpack.sv]] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../rtl/img_proc/raw10_unpack.sv
}
if { [get_files [list raw8_passthrough.sv]] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../rtl/img_proc/raw8_passthrough.sv
}
if { [get_files [list rgb565_gray_unpack.sv]] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../rtl/img_proc/rgb565_gray_unpack.sv
}
if { [get_files [list video_frame_normalizer.sv]] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../rtl/img_proc/video_frame_normalizer.sv
}
if { [get_files [list yuv422_crc_framebuffer_axis.sv]] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../rtl/img_proc/yuv422_crc_framebuffer_axis.sv
}
if { [get_files [list yuv422_gray_unpack.sv]] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../rtl/img_proc/yuv422_gray_unpack.sv
}
if { [get_files [list mipi_to_hdmi_vdma_loop_ref.v]] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../rtl/prototype/mipi_to_hdmi_vdma_loop_ref.v
}


# Proc to create BD bd
proc cr_bd_bd { parentCell } {
# The design that will be created by this Tcl proc contains the following 
# module references:
# axis_y8_to_vdma32_ref, axis_vdma32_to_y8_ref, mipi_to_hdmi_vdma_loop_ref



  # CHANGE DESIGN NAME HERE
  set design_name bd

  common::send_gid_msg -ssname BD::TCL -id 2010 -severity "INFO" "Currently there is no design <$design_name> in project, so creating one..."

  create_bd_design $design_name

  set bCheckIPsPassed 1
  ##################################################################
  # CHECK IPs
  ##################################################################
  set bCheckIPs 1
  if { $bCheckIPs == 1 } {
     set list_check_ips "\ 
  xilinx.com:ip:processing_system7:*\
  xilinx.com:ip:proc_sys_reset:*\
  xilinx.com:ip:axi_vdma:*\
  xilinx.com:ip:axis_clock_converter:*\
  xilinx.com:ip:axis_subset_converter:*\
  xilinx.com:ip:axi_gpio:*\
  "

   set list_ips_missing ""
   common::send_gid_msg -ssname BD::TCL -id 2011 -severity "INFO" "Checking if the following IPs exist in the project's IP catalog: $list_check_ips ."

   foreach ip_vlnv $list_check_ips {
      set ip_obj [get_ipdefs -all $ip_vlnv]
      if { $ip_obj eq "" } {
         lappend list_ips_missing $ip_vlnv
      }
   }

   if { $list_ips_missing ne "" } {
      catch {common::send_gid_msg -ssname BD::TCL -id 2012 -severity "ERROR" "The following IPs are not found in the IP Catalog:\n  $list_ips_missing\n\nResolution: Please add the repository containing the IP(s) to the project." }
      set bCheckIPsPassed 0
   }

  }

  ##################################################################
  # CHECK Modules
  ##################################################################
  set bCheckModules 1
  if { $bCheckModules == 1 } {
     set list_check_mods "\ 
  axis_y8_to_vdma32_ref\
  axis_vdma32_to_y8_ref\
  mipi_to_hdmi_vdma_loop_ref\
  "

   set list_mods_missing ""
   common::send_gid_msg -ssname BD::TCL -id 2020 -severity "INFO" "Checking if the following modules exist in the project's sources: $list_check_mods ."

   foreach mod_vlnv $list_check_mods {
      if { [can_resolve_reference $mod_vlnv] == 0 } {
         lappend list_mods_missing $mod_vlnv
      }
   }

   if { $list_mods_missing ne "" } {
      catch {common::send_gid_msg -ssname BD::TCL -id 2021 -severity "ERROR" "The following module(s) are not found in the project: $list_mods_missing" }
      common::send_gid_msg -ssname BD::TCL -id 2022 -severity "INFO" "Please add source files for the missing module(s) above."
      set bCheckIPsPassed 0
   }
}

  if { $bCheckIPsPassed != 1 } {
    common::send_gid_msg -ssname BD::TCL -id 2023 -severity "WARNING" "Will not continue with creation of design due to the error(s) above."
    return 3
  }

  variable script_folder

  if { $parentCell eq "" } {
     set parentCell [get_bd_cells /]
  }

  # Get object for parentCell
  set parentObj [get_bd_cells $parentCell]
  if { $parentObj == "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2090 -severity "ERROR" "Unable to find parent cell <$parentCell>!"}
     return
  }

  # Make sure parentObj is hier blk
  set parentType [get_property TYPE $parentObj]
  if { $parentType ne "hier" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2091 -severity "ERROR" "Parent <$parentObj> has TYPE = <$parentType>. Expected to be <hier>."}
     return
  }

  # Save current instance; Restore later
  set oldCurInst [current_bd_instance .]

  # Set parent object as current
  current_bd_instance $parentObj


  # Create interface ports
  set DDR [ create_bd_intf_port -mode Master -vlnv xilinx.com:interface:ddrx_rtl:1.0 DDR ]

  set FIXED_IO [ create_bd_intf_port -mode Master -vlnv xilinx.com:display_processing_system7:fixedio_rtl:1.0 FIXED_IO ]


  # Create ports
  set sysclk [ create_bd_port -dir I -type clk -freq_hz 125000000 sysclk ]
  set led [ create_bd_port -dir O -from 3 -to 0 led ]
  set dphy_hs_clock_clk_p [ create_bd_port -dir I dphy_hs_clock_clk_p ]
  set dphy_hs_clock_clk_n [ create_bd_port -dir I dphy_hs_clock_clk_n ]
  set dphy_data_hs_p [ create_bd_port -dir I -from 1 -to 0 dphy_data_hs_p ]
  set dphy_data_hs_n [ create_bd_port -dir I -from 1 -to 0 dphy_data_hs_n ]
  set dphy_clk_lp_p [ create_bd_port -dir I dphy_clk_lp_p ]
  set dphy_clk_lp_n [ create_bd_port -dir I dphy_clk_lp_n ]
  set dphy_data_lp_p [ create_bd_port -dir I -from 1 -to 0 dphy_data_lp_p ]
  set dphy_data_lp_n [ create_bd_port -dir I -from 1 -to 0 dphy_data_lp_n ]
  set cam_clk [ create_bd_port -dir O cam_clk ]
  set cam_gpio [ create_bd_port -dir O cam_gpio ]
  set cam_scl [ create_bd_port -dir IO cam_scl ]
  set cam_sda [ create_bd_port -dir IO cam_sda ]
  set hdmi_tx_hpd [ create_bd_port -dir I hdmi_tx_hpd ]
  set hdmi_tx_clk_p [ create_bd_port -dir O hdmi_tx_clk_p ]
  set hdmi_tx_clk_n [ create_bd_port -dir O hdmi_tx_clk_n ]
  set hdmi_tx_p [ create_bd_port -dir O -from 2 -to 0 hdmi_tx_p ]
  set hdmi_tx_n [ create_bd_port -dir O -from 2 -to 0 hdmi_tx_n ]
  set hdmi_tx_scl [ create_bd_port -dir O hdmi_tx_scl ]
  set hdmi_tx_sda [ create_bd_port -dir IO hdmi_tx_sda ]
  set hdmi_tx_cec [ create_bd_port -dir O hdmi_tx_cec ]

  # Create instance: ps7, and set properties
  set ps7 [ create_bd_cell -type ip -vlnv xilinx.com:ip:processing_system7 ps7 ]
  set_property -dict [list \
    CONFIG.PCW_ACT_APU_PERIPHERAL_FREQMHZ {666.666687} \
    CONFIG.PCW_ACT_CAN_PERIPHERAL_FREQMHZ {10.000000} \
    CONFIG.PCW_ACT_DCI_PERIPHERAL_FREQMHZ {10.158730} \
    CONFIG.PCW_ACT_ENET0_PERIPHERAL_FREQMHZ {10.000000} \
    CONFIG.PCW_ACT_ENET1_PERIPHERAL_FREQMHZ {10.000000} \
    CONFIG.PCW_ACT_FPGA0_PERIPHERAL_FREQMHZ {100.000000} \
    CONFIG.PCW_ACT_FPGA1_PERIPHERAL_FREQMHZ {10.000000} \
    CONFIG.PCW_ACT_FPGA2_PERIPHERAL_FREQMHZ {10.000000} \
    CONFIG.PCW_ACT_FPGA3_PERIPHERAL_FREQMHZ {10.000000} \
    CONFIG.PCW_ACT_PCAP_PERIPHERAL_FREQMHZ {200.000000} \
    CONFIG.PCW_ACT_QSPI_PERIPHERAL_FREQMHZ {10.000000} \
    CONFIG.PCW_ACT_SDIO_PERIPHERAL_FREQMHZ {10.000000} \
    CONFIG.PCW_ACT_SMC_PERIPHERAL_FREQMHZ {10.000000} \
    CONFIG.PCW_ACT_SPI_PERIPHERAL_FREQMHZ {10.000000} \
    CONFIG.PCW_ACT_TPIU_PERIPHERAL_FREQMHZ {200.000000} \
    CONFIG.PCW_ACT_TTC0_CLK0_PERIPHERAL_FREQMHZ {111.111115} \
    CONFIG.PCW_ACT_TTC0_CLK1_PERIPHERAL_FREQMHZ {111.111115} \
    CONFIG.PCW_ACT_TTC0_CLK2_PERIPHERAL_FREQMHZ {111.111115} \
    CONFIG.PCW_ACT_TTC1_CLK0_PERIPHERAL_FREQMHZ {111.111115} \
    CONFIG.PCW_ACT_TTC1_CLK1_PERIPHERAL_FREQMHZ {111.111115} \
    CONFIG.PCW_ACT_TTC1_CLK2_PERIPHERAL_FREQMHZ {111.111115} \
    CONFIG.PCW_ACT_UART_PERIPHERAL_FREQMHZ {10.000000} \
    CONFIG.PCW_ACT_WDT_PERIPHERAL_FREQMHZ {111.111115} \
    CONFIG.PCW_CLK0_FREQ {100000000} \
    CONFIG.PCW_CLK1_FREQ {10000000} \
    CONFIG.PCW_CLK2_FREQ {10000000} \
    CONFIG.PCW_CLK3_FREQ {10000000} \
    CONFIG.PCW_DDR_RAM_HIGHADDR {0x3FFFFFFF} \
    CONFIG.PCW_EN_CLK0_PORT {1} \
    CONFIG.PCW_EN_RST0_PORT {1} \
    CONFIG.PCW_FCLK_CLK0_BUF {TRUE} \
    CONFIG.PCW_FPGA0_PERIPHERAL_FREQMHZ {100.000000} \
    CONFIG.PCW_FPGA_FCLK0_ENABLE {1} \
    CONFIG.PCW_UIPARAM_ACT_DDR_FREQ_MHZ {533.333374} \
    CONFIG.PCW_UIPARAM_DDR_PARTNO {MT41K256M16 RE-125} \
    CONFIG.PCW_USE_M_AXI_GP0 {1} \
    CONFIG.PCW_USE_S_AXI_HP0 {1} \
  ] $ps7


  # Create instance: rst0, and set properties
  set rst0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:proc_sys_reset rst0 ]

  # Create instance: axi_vdma_0, and set properties
  set axi_vdma_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_vdma axi_vdma_0 ]
  set_property -dict [list \
    CONFIG.c_include_mm2s {1} \
    CONFIG.c_include_mm2s_dre {0} \
    CONFIG.c_include_s2mm {1} \
    CONFIG.c_include_s2mm_dre {0} \
    CONFIG.c_m_axi_mm2s_data_width {64} \
    CONFIG.c_m_axi_s2mm_data_width {64} \
    CONFIG.c_m_axis_mm2s_tdata_width {32} \
    CONFIG.c_mm2s_genlock_mode {0} \
    CONFIG.c_mm2s_genlock_repeat_en {0} \
    CONFIG.c_mm2s_linebuffer_depth {1024} \
    CONFIG.c_num_fstores {3} \
    CONFIG.c_s2mm_genlock_mode {2} \
    CONFIG.c_s2mm_genlock_repeat_en {0} \
    CONFIG.c_s2mm_linebuffer_depth {1024} \
    CONFIG.c_use_mm2s_fsync {0} \
    CONFIG.c_use_s2mm_fsync {2} \
  ] $axi_vdma_0


  # Create instance: ic0, and set properties
  set ic0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_interconnect ic0 ]
  set_property -dict [list \
    CONFIG.NUM_MI {1} \
    CONFIG.NUM_SI {2} \
  ] $ic0


  # Create instance: pack_s2mm, and set properties
  set block_name axis_y8_to_vdma32_ref
  set block_cell_name pack_s2mm
  if { [catch {set pack_s2mm [create_bd_cell -type module -reference $block_name $block_cell_name] } errmsg] } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2095 -severity "ERROR" "Unable to add referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   } elseif { $pack_s2mm eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2096 -severity "ERROR" "Unable to referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   }
  
  # Create instance: unpack_mm2s, and set properties
  set block_name axis_vdma32_to_y8_ref
  set block_cell_name unpack_mm2s
  if { [catch {set unpack_mm2s [create_bd_cell -type module -reference $block_name $block_cell_name] } errmsg] } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2095 -severity "ERROR" "Unable to add referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   } elseif { $unpack_mm2s eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2096 -severity "ERROR" "Unable to referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   }
  
  # Create instance: cc_mm2s, and set properties
  set cc_mm2s [ create_bd_cell -type ip -vlnv xilinx.com:ip:axis_clock_converter cc_mm2s ]
  set_property -dict [list \
    CONFIG.HAS_TLAST {1} \
    CONFIG.TDATA_NUM_BYTES {1} \
    CONFIG.TUSER_WIDTH {1} \
  ] $cc_mm2s


  # Create instance: sub_y_to_rgb, and set properties
  set sub_y_to_rgb [ create_bd_cell -type ip -vlnv xilinx.com:ip:axis_subset_converter sub_y_to_rgb ]
  set_property -dict [list \
    CONFIG.M_HAS_TKEEP {0} \
    CONFIG.M_HAS_TLAST {1} \
    CONFIG.M_HAS_TREADY {1} \
    CONFIG.M_HAS_TSTRB {0} \
    CONFIG.M_TDATA_NUM_BYTES {3} \
    CONFIG.M_TDEST_WIDTH {0} \
    CONFIG.M_TID_WIDTH {0} \
    CONFIG.M_TUSER_WIDTH {1} \
    CONFIG.S_HAS_TKEEP {0} \
    CONFIG.S_HAS_TLAST {1} \
    CONFIG.S_HAS_TREADY {1} \
    CONFIG.S_HAS_TSTRB {0} \
    CONFIG.S_TDATA_NUM_BYTES {1} \
    CONFIG.S_TDEST_WIDTH {0} \
    CONFIG.S_TID_WIDTH {0} \
    CONFIG.S_TUSER_WIDTH {1} \
    CONFIG.TDATA_REMAP {tdata[7:0],tdata[7:0],tdata[7:0]} \
    CONFIG.TLAST_REMAP {tlast[0]} \
    CONFIG.TUSER_REMAP {tuser[0:0]} \
  ] $sub_y_to_rgb


  # Create instance: dbg_gpio, and set properties
  set dbg_gpio [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_gpio dbg_gpio ]
  set_property -dict [list \
    CONFIG.C_ALL_INPUTS {1} \
    CONFIG.C_ALL_OUTPUTS_2 {1} \
    CONFIG.C_GPIO2_WIDTH {8} \
    CONFIG.C_GPIO_WIDTH {32} \
    CONFIG.C_IS_DUAL {1} \
  ] $dbg_gpio


  # Create instance: sccb_gpio, and set properties
  set sccb_gpio [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_gpio sccb_gpio ]
  set_property -dict [list \
    CONFIG.C_ALL_INPUTS_2 {1} \
    CONFIG.C_ALL_OUTPUTS {1} \
    CONFIG.C_GPIO2_WIDTH {32} \
    CONFIG.C_GPIO_WIDTH {32} \
    CONFIG.C_IS_DUAL {1} \
  ] $sccb_gpio


  # Create instance: idelay_gpio, and set properties
  set idelay_gpio [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_gpio idelay_gpio ]
  set_property -dict [list \
    CONFIG.C_ALL_INPUTS_2 {1} \
    CONFIG.C_ALL_OUTPUTS {1} \
    CONFIG.C_DOUT_DEFAULT {0x40000000} \
    CONFIG.C_GPIO2_WIDTH {32} \
    CONFIG.C_GPIO_WIDTH {32} \
    CONFIG.C_IS_DUAL {1} \
  ] $idelay_gpio


  # Create instance: bitslip_gpio, and set properties
  set bitslip_gpio [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_gpio bitslip_gpio ]
  set_property -dict [list \
    CONFIG.C_ALL_INPUTS_2 {1} \
    CONFIG.C_ALL_OUTPUTS {1} \
    CONFIG.C_GPIO2_WIDTH {32} \
    CONFIG.C_GPIO_WIDTH {32} \
    CONFIG.C_IS_DUAL {1} \
  ] $bitslip_gpio


  # Create instance: frame_lines_gpio, and set properties
  set frame_lines_gpio [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_gpio frame_lines_gpio ]
  set_property -dict [list \
    CONFIG.C_ALL_INPUTS_2 {1} \
    CONFIG.C_ALL_OUTPUTS {1} \
    CONFIG.C_DOUT_DEFAULT {0xC24501E0} \
    CONFIG.C_GPIO2_WIDTH {32} \
    CONFIG.C_GPIO_WIDTH {32} \
    CONFIG.C_IS_DUAL {1} \
  ] $frame_lines_gpio


  # Create instance: rawcap_gpio, and set properties
  set rawcap_gpio [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_gpio rawcap_gpio ]
  set_property -dict [list \
    CONFIG.C_ALL_INPUTS_2 {1} \
    CONFIG.C_ALL_OUTPUTS {1} \
    CONFIG.C_GPIO2_WIDTH {32} \
    CONFIG.C_GPIO_WIDTH {32} \
    CONFIG.C_IS_DUAL {1} \
  ] $rawcap_gpio


  # Create instance: core0, and set properties
  set block_name mipi_to_hdmi_vdma_loop_ref
  set block_cell_name core0
  if { [catch {set core0 [create_bd_cell -type module -reference $block_name $block_cell_name] } errmsg] } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2095 -severity "ERROR" "Unable to add referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   } elseif { $core0 eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2096 -severity "ERROR" "Unable to referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   }
    set_property -dict [list \
    CONFIG.CAPTURE_RAW_PAYLOAD {0} \
    CONFIG.OV5640_FORMAT_CTRL_4300 {01101111} \
    CONFIG.OV5640_ISP_CTRL_5000 {"10100111"} \
    CONFIG.OV5640_ISP_CTRL_5001 {"10000011"} \
    CONFIG.OV5640_MIPI_CTRL_4800 {00010100} \
    CONFIG.OV5640_TEST_PATTERN_ENABLE {0} \
    CONFIG.PROBE_IDELAY_TAP {16} \
    CONFIG.PROBE_LANE1_BITSLIP_SWEEP {0} \
    CONFIG.STREAM_PAIRING {0} \
    CONFIG.USE_RGB565_GRAY {0} \
  ] $core0


  # Create instance: ps7_axi_periph, and set properties
  set ps7_axi_periph [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_interconnect ps7_axi_periph ]
  set_property CONFIG.NUM_MI {7} $ps7_axi_periph


  # Create interface connections
  connect_bd_intf_net -intf_net axi_vdma_0_M_AXIS_MM2S [get_bd_intf_pins axi_vdma_0/M_AXIS_MM2S] [get_bd_intf_pins unpack_mm2s/S_AXIS]
  connect_bd_intf_net -intf_net axi_vdma_0_M_AXI_MM2S [get_bd_intf_pins axi_vdma_0/M_AXI_MM2S] [get_bd_intf_pins ic0/S01_AXI]
  connect_bd_intf_net -intf_net axi_vdma_0_M_AXI_S2MM [get_bd_intf_pins axi_vdma_0/M_AXI_S2MM] [get_bd_intf_pins ic0/S00_AXI]
  connect_bd_intf_net -intf_net cc_mm2s_M_AXIS [get_bd_intf_pins cc_mm2s/M_AXIS] [get_bd_intf_pins sub_y_to_rgb/S_AXIS]
  connect_bd_intf_net -intf_net core0_m_axis_capture [get_bd_intf_pins core0/m_axis_capture] [get_bd_intf_pins pack_s2mm/S_AXIS]
  connect_bd_intf_net -intf_net ic0_M00_AXI [get_bd_intf_pins ic0/M00_AXI] [get_bd_intf_pins ps7/S_AXI_HP0]
  connect_bd_intf_net -intf_net pack_s2mm_M_AXIS [get_bd_intf_pins pack_s2mm/M_AXIS] [get_bd_intf_pins axi_vdma_0/S_AXIS_S2MM]
  connect_bd_intf_net -intf_net ps7_DDR [get_bd_intf_ports DDR] [get_bd_intf_pins ps7/DDR]
  connect_bd_intf_net -intf_net ps7_FIXED_IO [get_bd_intf_ports FIXED_IO] [get_bd_intf_pins ps7/FIXED_IO]
  connect_bd_intf_net -intf_net ps7_M_AXI_GP0 [get_bd_intf_pins ps7/M_AXI_GP0] [get_bd_intf_pins ps7_axi_periph/S00_AXI]
  connect_bd_intf_net -intf_net ps7_axi_periph_M00_AXI [get_bd_intf_pins ps7_axi_periph/M00_AXI] [get_bd_intf_pins axi_vdma_0/S_AXI_LITE]
  connect_bd_intf_net -intf_net ps7_axi_periph_M01_AXI [get_bd_intf_pins ps7_axi_periph/M01_AXI] [get_bd_intf_pins dbg_gpio/S_AXI]
  connect_bd_intf_net -intf_net ps7_axi_periph_M02_AXI [get_bd_intf_pins ps7_axi_periph/M02_AXI] [get_bd_intf_pins sccb_gpio/S_AXI]
  connect_bd_intf_net -intf_net ps7_axi_periph_M03_AXI [get_bd_intf_pins ps7_axi_periph/M03_AXI] [get_bd_intf_pins idelay_gpio/S_AXI]
  connect_bd_intf_net -intf_net ps7_axi_periph_M04_AXI [get_bd_intf_pins ps7_axi_periph/M04_AXI] [get_bd_intf_pins bitslip_gpio/S_AXI]
  connect_bd_intf_net -intf_net ps7_axi_periph_M05_AXI [get_bd_intf_pins ps7_axi_periph/M05_AXI] [get_bd_intf_pins frame_lines_gpio/S_AXI]
  connect_bd_intf_net -intf_net ps7_axi_periph_M06_AXI [get_bd_intf_pins ps7_axi_periph/M06_AXI] [get_bd_intf_pins rawcap_gpio/S_AXI]
  connect_bd_intf_net -intf_net sub_y_to_rgb_M_AXIS [get_bd_intf_pins sub_y_to_rgb/M_AXIS] [get_bd_intf_pins core0/s_axis_hdmi]
  connect_bd_intf_net -intf_net unpack_mm2s_M_AXIS [get_bd_intf_pins unpack_mm2s/M_AXIS] [get_bd_intf_pins cc_mm2s/S_AXIS]

  # Create port connections
  connect_bd_net -net Net  [get_bd_ports cam_scl] \
  [get_bd_pins core0/cam_scl]
  connect_bd_net -net Net1  [get_bd_ports cam_sda] \
  [get_bd_pins core0/cam_sda]
  connect_bd_net -net Net2  [get_bd_ports hdmi_tx_sda] \
  [get_bd_pins core0/hdmi_tx_sda]
  connect_bd_net -net bitslip_gpio_gpio_io_o  [get_bd_pins bitslip_gpio/gpio_io_o] \
  [get_bd_pins core0/bitslip_runtime_word_in]
  connect_bd_net -net core0_bitslip_runtime_status_out  [get_bd_pins core0/bitslip_runtime_status_out] \
  [get_bd_pins bitslip_gpio/gpio2_io_i]
  connect_bd_net -net core0_cam_clk  [get_bd_pins core0/cam_clk] \
  [get_bd_ports cam_clk]
  connect_bd_net -net core0_cam_gpio  [get_bd_pins core0/cam_gpio] \
  [get_bd_ports cam_gpio]
  connect_bd_net -net core0_capture_debug  [get_bd_pins core0/capture_debug] \
  [get_bd_pins dbg_gpio/gpio_io_i]
  connect_bd_net -net core0_frame_lines_runtime_status_out  [get_bd_pins core0/frame_lines_runtime_status_out] \
  [get_bd_pins frame_lines_gpio/gpio2_io_i]
  connect_bd_net -net core0_hdmi_tx_cec  [get_bd_pins core0/hdmi_tx_cec] \
  [get_bd_ports hdmi_tx_cec]
  connect_bd_net -net core0_hdmi_tx_clk_n  [get_bd_pins core0/hdmi_tx_clk_n] \
  [get_bd_ports hdmi_tx_clk_n]
  connect_bd_net -net core0_hdmi_tx_clk_p  [get_bd_pins core0/hdmi_tx_clk_p] \
  [get_bd_ports hdmi_tx_clk_p]
  connect_bd_net -net core0_hdmi_tx_n  [get_bd_pins core0/hdmi_tx_n] \
  [get_bd_ports hdmi_tx_n]
  connect_bd_net -net core0_hdmi_tx_p  [get_bd_pins core0/hdmi_tx_p] \
  [get_bd_ports hdmi_tx_p]
  connect_bd_net -net core0_hdmi_tx_scl  [get_bd_pins core0/hdmi_tx_scl] \
  [get_bd_ports hdmi_tx_scl]
  connect_bd_net -net core0_idelay_runtime_status_out  [get_bd_pins core0/idelay_runtime_status_out] \
  [get_bd_pins idelay_gpio/gpio2_io_i]
  connect_bd_net -net core0_led  [get_bd_pins core0/led] \
  [get_bd_ports led]
  connect_bd_net -net core0_pix_aresetn_out  [get_bd_pins core0/pix_aresetn_out] \
  [get_bd_pins cc_mm2s/m_axis_aresetn] \
  [get_bd_pins sub_y_to_rgb/aresetn]
  connect_bd_net -net core0_pix_clk_out  [get_bd_pins core0/pix_clk_out] \
  [get_bd_pins cc_mm2s/m_axis_aclk] \
  [get_bd_pins sub_y_to_rgb/aclk]
  connect_bd_net -net core0_rawcap_status_out  [get_bd_pins core0/rawcap_status_out] \
  [get_bd_pins rawcap_gpio/gpio2_io_i]
  connect_bd_net -net core0_sccb_rt_write_status_out  [get_bd_pins core0/sccb_rt_write_status_out] \
  [get_bd_pins sccb_gpio/gpio2_io_i]
  connect_bd_net -net dbg_gpio_gpio2_io_o  [get_bd_pins dbg_gpio/gpio2_io_o] \
  [get_bd_pins core0/debug_page_sel]
  connect_bd_net -net dphy_clk_lp_n_1  [get_bd_ports dphy_clk_lp_n] \
  [get_bd_pins core0/dphy_clk_lp_n]
  connect_bd_net -net dphy_clk_lp_p_1  [get_bd_ports dphy_clk_lp_p] \
  [get_bd_pins core0/dphy_clk_lp_p]
  connect_bd_net -net dphy_data_hs_n_1  [get_bd_ports dphy_data_hs_n] \
  [get_bd_pins core0/dphy_data_hs_n]
  connect_bd_net -net dphy_data_hs_p_1  [get_bd_ports dphy_data_hs_p] \
  [get_bd_pins core0/dphy_data_hs_p]
  connect_bd_net -net dphy_data_lp_n_1  [get_bd_ports dphy_data_lp_n] \
  [get_bd_pins core0/dphy_data_lp_n]
  connect_bd_net -net dphy_data_lp_p_1  [get_bd_ports dphy_data_lp_p] \
  [get_bd_pins core0/dphy_data_lp_p]
  connect_bd_net -net dphy_hs_clock_clk_n_1  [get_bd_ports dphy_hs_clock_clk_n] \
  [get_bd_pins core0/dphy_hs_clock_clk_n]
  connect_bd_net -net dphy_hs_clock_clk_p_1  [get_bd_ports dphy_hs_clock_clk_p] \
  [get_bd_pins core0/dphy_hs_clock_clk_p]
  connect_bd_net -net frame_lines_gpio_gpio_io_o  [get_bd_pins frame_lines_gpio/gpio_io_o] \
  [get_bd_pins core0/frame_lines_runtime_word_in]
  connect_bd_net -net hdmi_tx_hpd_1  [get_bd_ports hdmi_tx_hpd] \
  [get_bd_pins core0/hdmi_tx_hpd]
  connect_bd_net -net idelay_gpio_gpio_io_o  [get_bd_pins idelay_gpio/gpio_io_o] \
  [get_bd_pins core0/idelay_runtime_word_in]
  connect_bd_net -net ps7_FCLK_CLK0  [get_bd_pins ps7/FCLK_CLK0] \
  [get_bd_pins rst0/slowest_sync_clk] \
  [get_bd_pins ps7/S_AXI_HP0_ACLK] \
  [get_bd_pins core0/capture_aclk] \
  [get_bd_pins axi_vdma_0/s_axi_lite_aclk] \
  [get_bd_pins axi_vdma_0/m_axi_s2mm_aclk] \
  [get_bd_pins axi_vdma_0/m_axi_mm2s_aclk] \
  [get_bd_pins axi_vdma_0/s_axis_s2mm_aclk] \
  [get_bd_pins axi_vdma_0/m_axis_mm2s_aclk] \
  [get_bd_pins pack_s2mm/aclk] \
  [get_bd_pins unpack_mm2s/aclk] \
  [get_bd_pins cc_mm2s/s_axis_aclk] \
  [get_bd_pins dbg_gpio/s_axi_aclk] \
  [get_bd_pins sccb_gpio/s_axi_aclk] \
  [get_bd_pins idelay_gpio/s_axi_aclk] \
  [get_bd_pins bitslip_gpio/s_axi_aclk] \
  [get_bd_pins frame_lines_gpio/s_axi_aclk] \
  [get_bd_pins rawcap_gpio/s_axi_aclk] \
  [get_bd_pins ps7_axi_periph/M00_ACLK] \
  [get_bd_pins ps7/M_AXI_GP0_ACLK] \
  [get_bd_pins ps7_axi_periph/S00_ACLK] \
  [get_bd_pins ps7_axi_periph/ACLK] \
  [get_bd_pins ps7_axi_periph/M01_ACLK] \
  [get_bd_pins ps7_axi_periph/M02_ACLK] \
  [get_bd_pins ps7_axi_periph/M03_ACLK] \
  [get_bd_pins ps7_axi_periph/M04_ACLK] \
  [get_bd_pins ps7_axi_periph/M05_ACLK] \
  [get_bd_pins ps7_axi_periph/M06_ACLK] \
  [get_bd_pins ic0/ACLK] \
  [get_bd_pins ic0/S00_ACLK] \
  [get_bd_pins ic0/S01_ACLK] \
  [get_bd_pins ic0/M00_ACLK]
  connect_bd_net -net ps7_FCLK_RESET0_N  [get_bd_pins ps7/FCLK_RESET0_N] \
  [get_bd_pins rst0/ext_reset_in]
  connect_bd_net -net rawcap_gpio_gpio_io_o  [get_bd_pins rawcap_gpio/gpio_io_o] \
  [get_bd_pins core0/rawcap_word_in]
  connect_bd_net -net rst0_peripheral_aresetn  [get_bd_pins rst0/peripheral_aresetn] \
  [get_bd_pins core0/capture_aresetn] \
  [get_bd_pins axi_vdma_0/axi_resetn] \
  [get_bd_pins pack_s2mm/aresetn] \
  [get_bd_pins unpack_mm2s/aresetn] \
  [get_bd_pins cc_mm2s/s_axis_aresetn] \
  [get_bd_pins dbg_gpio/s_axi_aresetn] \
  [get_bd_pins sccb_gpio/s_axi_aresetn] \
  [get_bd_pins idelay_gpio/s_axi_aresetn] \
  [get_bd_pins bitslip_gpio/s_axi_aresetn] \
  [get_bd_pins frame_lines_gpio/s_axi_aresetn] \
  [get_bd_pins rawcap_gpio/s_axi_aresetn] \
  [get_bd_pins ps7_axi_periph/M00_ARESETN] \
  [get_bd_pins ps7_axi_periph/S00_ARESETN] \
  [get_bd_pins ps7_axi_periph/ARESETN] \
  [get_bd_pins ps7_axi_periph/M01_ARESETN] \
  [get_bd_pins ps7_axi_periph/M02_ARESETN] \
  [get_bd_pins ps7_axi_periph/M03_ARESETN] \
  [get_bd_pins ps7_axi_periph/M04_ARESETN] \
  [get_bd_pins ps7_axi_periph/M05_ARESETN] \
  [get_bd_pins ps7_axi_periph/M06_ARESETN] \
  [get_bd_pins ic0/ARESETN] \
  [get_bd_pins ic0/S00_ARESETN] \
  [get_bd_pins ic0/S01_ARESETN] \
  [get_bd_pins ic0/M00_ARESETN]
  connect_bd_net -net sccb_gpio_gpio_io_o  [get_bd_pins sccb_gpio/gpio_io_o] \
  [get_bd_pins core0/sccb_rt_write_word_in]
  connect_bd_net -net sysclk_1  [get_bd_ports sysclk] \
  [get_bd_pins core0/sysclk]

  # Create address segments
  assign_bd_address -offset 0x43000000 -range 0x00010000 -target_address_space [get_bd_addr_spaces ps7/Data] [get_bd_addr_segs axi_vdma_0/S_AXI_LITE/Reg] -force
  assign_bd_address -offset 0x41230000 -range 0x00010000 -target_address_space [get_bd_addr_spaces ps7/Data] [get_bd_addr_segs bitslip_gpio/S_AXI/Reg] -force
  assign_bd_address -offset 0x41200000 -range 0x00010000 -target_address_space [get_bd_addr_spaces ps7/Data] [get_bd_addr_segs dbg_gpio/S_AXI/Reg] -force
  assign_bd_address -offset 0x41240000 -range 0x00010000 -target_address_space [get_bd_addr_spaces ps7/Data] [get_bd_addr_segs frame_lines_gpio/S_AXI/Reg] -force
  assign_bd_address -offset 0x41220000 -range 0x00010000 -target_address_space [get_bd_addr_spaces ps7/Data] [get_bd_addr_segs idelay_gpio/S_AXI/Reg] -force
  assign_bd_address -offset 0x41250000 -range 0x00010000 -target_address_space [get_bd_addr_spaces ps7/Data] [get_bd_addr_segs rawcap_gpio/S_AXI/Reg] -force
  assign_bd_address -offset 0x41210000 -range 0x00010000 -target_address_space [get_bd_addr_spaces ps7/Data] [get_bd_addr_segs sccb_gpio/S_AXI/Reg] -force
  assign_bd_address -offset 0x00000000 -range 0x40000000 -target_address_space [get_bd_addr_spaces axi_vdma_0/Data_MM2S] [get_bd_addr_segs ps7/S_AXI_HP0/HP0_DDR_LOWOCM] -force
  assign_bd_address -offset 0x00000000 -range 0x40000000 -target_address_space [get_bd_addr_spaces axi_vdma_0/Data_S2MM] [get_bd_addr_segs ps7/S_AXI_HP0/HP0_DDR_LOWOCM] -force


  # Restore current instance
  current_bd_instance $oldCurInst

  validate_bd_design
  save_bd_design
  close_bd_design $design_name 
}
# End of cr_bd_bd()

cr_bd_bd ""
set_property REGISTERED_WITH_MANAGER "1" [get_files bd.bd ] 
set_property SYNTH_CHECKPOINT_MODE "Hierarchical" [get_files bd.bd ] 

#call make_wrapper to create wrapper files
if { [get_property IS_LOCKED [ get_files -norecurse [list bd.bd]] ] == 1  } {
  import_files -fileset sources_1 [file normalize "${origin_dir}/../vloop_probes2/vloop.gen/sources_1/bd/bd/hdl/bd_wrapper.v" ]
} else {
  set wrapper_path [make_wrapper -fileset sources_1 -files [ get_files -norecurse [list bd.bd]] -top]
  add_files -norecurse -fileset sources_1 $wrapper_path
}


set idrFlowPropertiesConstraints ""
catch {
 set idrFlowPropertiesConstraints [get_param runs.disableIDRFlowPropertyConstraints]
 set_param runs.disableIDRFlowPropertyConstraints 1
}

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
    create_run -name synth_1 -part xc7z020clg400-1 -flow {Vivado Synthesis 2024} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2024" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Synthesis Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'synth_1_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0] "" ] } {
  create_report_config -report_name synth_1_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs synth_1
}
set obj [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs synth_1]
set_property -name "needs_refresh" -value "1" -objects $obj
set_property -name "part" -value "xc7z020clg400-1" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
    create_run -name impl_1 -part xc7z020clg400-1 -flow {Vivado Implementation 2024} -strategy "Performance_ExplorePostRoutePhysOpt" -report_strategy {No Reports} -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Performance_ExplorePostRoutePhysOpt" [get_runs impl_1]
  set_property flow "Vivado Implementation 2024" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Implementation Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'impl_1_init_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_init_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps init_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_opt_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_drc_0 -report_type report_drc:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_place_report_io_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0] "" ] } {
  create_report_config -report_name impl_1_place_report_io_0 -report_type report_io:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0] "" ] } {
  create_report_config -report_name impl_1_place_report_utilization_0 -report_type report_utilization:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_control_sets_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0] "" ] } {
  create_report_config -report_name impl_1_place_report_control_sets_0 -report_type report_control_sets:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0]
if { $obj != "" } {
set_property -name "options.verbose" -value "1" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_1' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_1 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_place_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_post_place_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_place_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_place_power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_route_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_route_report_drc_0 -report_type report_drc:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_methodology_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0] "" ] } {
  create_report_config -report_name impl_1_route_report_methodology_0 -report_type report_methodology:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_power_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0] "" ] } {
  create_report_config -report_name impl_1_route_report_power_0 -report_type report_power:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_route_status_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0] "" ] } {
  create_report_config -report_name impl_1_route_report_route_status_0 -report_type report_route_status:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_route_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_route_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_route_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_clock_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0] "" ] } {
  create_report_config -report_name impl_1_route_report_clock_utilization_0 -report_type report_clock_utilization:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_route_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
set obj [get_runs impl_1]
set_property -name "needs_refresh" -value "1" -objects $obj
set_property -name "part" -value "xc7z020clg400-1" -objects $obj
set_property -name "strategy" -value "Performance_ExplorePostRoutePhysOpt" -objects $obj
set_property -name "steps.opt_design.args.directive" -value "Explore" -objects $obj
set_property -name "steps.place_design.args.directive" -value "Explore" -objects $obj
set_property -name "steps.phys_opt_design.args.directive" -value "Explore" -objects $obj
set_property -name "steps.route_design.args.directive" -value "Explore" -objects $obj
set_property -name "steps.route_design.args.more options" -value {-tns_cleanup} -objects $obj
set_property -name "steps.post_route_phys_opt_design.is_enabled" -value "1" -objects $obj
set_property -name "steps.post_route_phys_opt_design.args.directive" -value "Explore" -objects $obj
set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj

# set the current impl run
current_run -implementation [get_runs impl_1]
catch {
 if { $idrFlowPropertiesConstraints != {} } {
   set_param runs.disableIDRFlowPropertyConstraints $idrFlowPropertiesConstraints
 }
}

puts "INFO: Project created:${_xil_proj_name_}"
# Create 'drc_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "drc_1" ] ] ""]} {
create_dashboard_gadget -name {drc_1} -type drc
}
set obj [get_dashboard_gadgets [ list "drc_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_drc_0" -objects $obj

# Create 'methodology_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "methodology_1" ] ] ""]} {
create_dashboard_gadget -name {methodology_1} -type methodology
}
set obj [get_dashboard_gadgets [ list "methodology_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_methodology_0" -objects $obj

# Create 'power_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "power_1" ] ] ""]} {
create_dashboard_gadget -name {power_1} -type power
}
set obj [get_dashboard_gadgets [ list "power_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_power_0" -objects $obj

# Create 'timing_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "timing_1" ] ] ""]} {
create_dashboard_gadget -name {timing_1} -type timing
}
set obj [get_dashboard_gadgets [ list "timing_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_timing_summary_0" -objects $obj

# Create 'utilization_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_1" ] ] ""]} {
create_dashboard_gadget -name {utilization_1} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_1" ] ]
set_property -name "reports" -value "synth_1#synth_1_synth_report_utilization_0" -objects $obj
set_property -name "run.step" -value "synth_design" -objects $obj
set_property -name "run.type" -value "synthesis" -objects $obj

# Create 'utilization_2' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_2" ] ] ""]} {
create_dashboard_gadget -name {utilization_2} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_2" ] ]
set_property -name "reports" -value "impl_1#impl_1_place_report_utilization_0" -objects $obj

move_dashboard_gadget -name {utilization_1} -row 0 -col 0
move_dashboard_gadget -name {power_1} -row 1 -col 0
move_dashboard_gadget -name {drc_1} -row 2 -col 0
move_dashboard_gadget -name {timing_1} -row 0 -col 1
move_dashboard_gadget -name {utilization_2} -row 1 -col 1
move_dashboard_gadget -name {methodology_1} -row 2 -col 1
